# Generated by Django 4.2.8 on 2026-01-01 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_signee', models.IntegerField(verbose_name='Quantité signée')),
                ('type', models.CharField(choices=[('RECEPTION', 'Réception'), ('VENTE', 'Vente'), ('AJUSTEMENT', 'Ajustement'), ('CASSE', 'Casse')], max_length=20, verbose_name='Type')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Référence')),
                ('reason', models.TextField(blank=True, verbose_name='Raison (obligatoire pour ajustement)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
