# Generated by Django 4.2.8 on 2026-01-02 14:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(max_length=200, verbose_name='Fournisseur')),
                ('date_achat', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'achat")),
                ('reference', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-date_achat', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='catalog.product', verbose_name='Produit')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_lines', to='stock.purchase', verbose_name='Achat')),
            ],
            options={
                'verbose_name': "Ligne d'achat",
                'verbose_name_plural': "Lignes d'achat",
                'ordering': ['created_at'],
                'unique_together': {('purchase', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['statut'], name='stock_purch_statut_418495_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['date_achat'], name='stock_purch_date_ac_4885bc_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['reference'], name='stock_purch_referen_657e76_idx'),
        ),
    ]
