# Generated by Django 4.2.8

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('stock', '0003_purchase_purchaseline_and_more'),
    ]

    operations = [
        # Add new field as nullable first
        migrations.AddField(
            model_name='purchase',
            name='fournisseur_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_as_supplier', to='clients.client', verbose_name='Fournisseur (Client)'),
        ),
        # Make reference nullable
        migrations.AlterField(
            model_name='purchase',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Référence'),
        ),
    ]

