# Generated by Django 4.2.8 on 2026-01-02 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stock', '0006_remove_old_fournisseur_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_as_supplier', to='clients.client', verbose_name='Fournisseur'),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Montant')),
                ('mode', models.CharField(choices=[('CASH', 'Espèces'), ('VIREMENT', 'Virement'), ('CB', 'Carte bancaire'), ('CHEQUE', 'Chèque')], max_length=20, verbose_name='Mode de paiement')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('reference', models.CharField(blank=True, max_length=200, verbose_name='Référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_payments', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='stock.purchase', verbose_name='Achat')),
            ],
            options={
                'verbose_name': 'Paiement achat',
                'verbose_name_plural': 'Paiements achats',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
