# Generated by Django 4.2.8 on 2026-01-02 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_create_invoices', models.BooleanField(blank=True, default=None, null=True, verbose_name='Créer des factures')),
                ('can_validate_invoices', models.BooleanField(blank=True, default=None, null=True, verbose_name='Valider des factures')),
                ('can_delete_invoices', models.BooleanField(blank=True, default=None, null=True, verbose_name='Supprimer des factures')),
                ('can_manage_payments', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer les paiements')),
                ('can_manage_stock', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer le stock')),
                ('can_adjust_stock', models.BooleanField(blank=True, default=None, null=True, verbose_name='Ajuster le stock')),
                ('can_manage_purchases', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer les achats')),
                ('can_manage_containers', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer les conteneurs')),
                ('can_validate_containers', models.BooleanField(blank=True, default=None, null=True, verbose_name='Valider les conteneurs')),
                ('can_manage_clients', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer les clients')),
                ('can_manage_client_prices', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer les prix clients')),
                ('can_manage_products', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer les produits')),
                ('can_view_reports', models.BooleanField(blank=True, default=None, null=True, verbose_name='Voir les rapports')),
                ('can_export_data', models.BooleanField(blank=True, default=None, null=True, verbose_name='Exporter les données')),
                ('can_manage_users', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer les utilisateurs')),
                ('can_manage_company_settings', models.BooleanField(blank=True, default=None, null=True, verbose_name='Gérer les paramètres entreprise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Permission utilisateur',
                'verbose_name_plural': 'Permissions utilisateur',
            },
        ),
    ]
