# Generated by Django 4.2.8 on 2026-01-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermission',
            name='can_adjust_stock',
            field=models.BooleanField(blank=True, null=True, verbose_name='Ajuster le stock'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_create_invoices',
            field=models.BooleanField(blank=True, null=True, verbose_name='Créer des factures'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_delete_invoices',
            field=models.BooleanField(blank=True, null=True, verbose_name='Supprimer des factures'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_export_data',
            field=models.BooleanField(blank=True, null=True, verbose_name='Exporter les données'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_client_prices',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer les prix clients'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_clients',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer les clients'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_company_settings',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer les paramètres entreprise'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_containers',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer les conteneurs'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_payments',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer les paiements'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_products',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer les produits'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_purchases',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer les achats'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_stock',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer le stock'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_manage_users',
            field=models.BooleanField(blank=True, null=True, verbose_name='Gérer les utilisateurs'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_validate_containers',
            field=models.BooleanField(blank=True, null=True, verbose_name='Valider les conteneurs'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_validate_invoices',
            field=models.BooleanField(blank=True, null=True, verbose_name='Valider des factures'),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='can_view_reports',
            field=models.BooleanField(blank=True, null=True, verbose_name='Voir les rapports'),
        ),
    ]
