# Generated by Django 4.2.8 on 2026-01-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.PositiveIntegerField(verbose_name="ID de l'entité")),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('before_json', models.JSONField(blank=True, null=True, verbose_name='État avant')),
                ('after_json', models.JSONField(blank=True, null=True, verbose_name='État après')),
                ('reason', models.TextField(blank=True, verbose_name='Raison')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name="Type d'entité")),
            ],
            options={
                'verbose_name': "Log d'audit",
                'verbose_name_plural': "Logs d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
