# Generated by Django 4.2.8 on 2026-01-01 15:29

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée'), ('AVOIR', 'Avoir')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('type', models.CharField(choices=[('LIVRAISON', 'Livraison'), ('RETRAIT', 'Retrait')], default='LIVRAISON', max_length=20, verbose_name='Type')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('paye', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Payé')),
                ('reste', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Reste à payer')),
                ('prochaine_date_relance', models.DateField(blank=True, null=True, verbose_name='Prochaine date de relance')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='Chemin PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('prix_unit_applique', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire appliqué (snapshot)')),
                ('total_ligne', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['invoice', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('mode', models.CharField(choices=[('CASH', 'Espèces'), ('VIREMENT', 'Virement'), ('CB', 'Carte bancaire')], max_length=20, verbose_name='Mode de paiement')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
