# Generated by Django 4.2.8 on 2026-01-02 00:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default="GOÛTS ET SAVEURS D'AFRIQUE", max_length=200, verbose_name="Nom de l'entreprise")),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('code_postal', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('pays', models.CharField(default='Sénégal', max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('site_web', models.URLField(blank=True, default='www.gsa-boissons.com', verbose_name='Site web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('numero_compte_bancaire', models.CharField(blank=True, max_length=100, verbose_name='Numéro de compte bancaire')),
                ('tva_taux', models.DecimalField(decimal_places=2, default=18.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('message_facture', models.TextField(default='Merci pour votre confiance !', verbose_name='Message sur la facture')),
            ],
            options={
                'verbose_name': "Paramètres de l'entreprise",
                'verbose_name_plural': "Paramètres de l'entreprise",
            },
        ),
        migrations.AlterModelOptions(
            name='invoiceline',
            options={'ordering': ['created_at'], 'verbose_name': 'Ligne de facture', 'verbose_name_plural': 'Lignes de facture'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'Paiement', 'verbose_name_plural': 'Paiements'},
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_statut_a19210_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_client__70fb2b_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_numero_43f86d_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='billing_inv_prochai_f47075_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceline',
            name='billing_inv_invoice_ea4b83_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='billing_pay_invoice_02be0c_idx',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_origine',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_ttc',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paye',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='prochaine_date_relance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée'), ('AVOIR', 'Avoir')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('LIVRAISON', 'Livraison'), ('RETRAIT', 'Retrait')], default='LIVRAISON', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='prix_unit_applique',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='total_ligne',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('VIREMENT', 'Virement'), ('CB', 'Carte bancaire')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='montant',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
