# Generated by Django 4.2.8 on 2026-01-02 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0003_companysettings_alter_invoiceline_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ACCEPTEE', 'Acceptée'), ('ANNULEE', 'Annulée'), ('AVOIR', 'Avoir')], default='BROUILLON', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'acceptation")),
                ('ip_address', models.CharField(max_length=45, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(verbose_name='User Agent')),
                ('pdf_hash', models.CharField(max_length=64, verbose_name='Hash PDF (SHA-256)')),
                ('acceptance_text_version', models.CharField(default='v1', max_length=20, verbose_name='Version texte acceptation')),
                ('accepted_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom acceptant')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance', to='billing.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Acceptation de facture',
                'verbose_name_plural': 'Acceptations de factures',
                'ordering': ['-accepted_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAcceptanceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Hash token (SHA-256)')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'utilisation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_acceptance_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptance_tokens', to='billing.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': "Token d'acceptation",
                'verbose_name_plural': "Tokens d'acceptation",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token_hash'], name='billing_inv_token_h_292e66_idx'), models.Index(fields=['expires_at'], name='billing_inv_expires_9d568f_idx')],
            },
        ),
    ]
