# Generated by Django 4.2.8 on 2026-01-02 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0004_alter_invoice_statut_invoiceacceptance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDEE', 'Validée'), ('ACCEPTEE', 'Acceptée'), ('CONTESTEE', 'Contestée'), ('ANNULEE', 'Annulée'), ('AVOIR', 'Avoir')], default='BROUILLON', max_length=20),
        ),
        migrations.CreateModel(
            name='InvoiceContestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contested_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de contestation')),
                ('contested_by_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du contestant')),
                ('contested_by_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du contestant')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Raison de la contestation')),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('resolved', models.BooleanField(default=False, verbose_name='Résolue')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='Notes de résolution')),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contestation', to='billing.invoice', verbose_name='Facture')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_contestations', to=settings.AUTH_USER_MODEL, verbose_name='Résolue par')),
            ],
            options={
                'verbose_name': 'Contestation de facture',
                'verbose_name_plural': 'Contestations de factures',
                'ordering': ['-contested_at'],
            },
        ),
    ]
