# Generated by Django 4.2.8 on 2026-01-04 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoice_statut_invoicecontestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='mode',
            field=models.CharField(choices=[('CASH', 'Espèces'), ('VIREMENT', 'Virement'), ('CB', 'Carte bancaire'), ('CHEQUE', 'Chèque')], max_length=20),
        ),
    ]
