# Generated by Django 4.2.8 on 2026-01-01 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('marque', models.CharField(blank=True, max_length=100, verbose_name='Marque')),
                ('unite_vente', models.CharField(choices=[('BOUTEILLE', 'Bouteille'), ('PACK', 'Pack'), ('CARTON', 'Carton')], default='BOUTEILLE', max_length=20, verbose_name='Unité de vente')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['nom'],
                'unique_together': {('nom', 'marque')},
            },
        ),
        migrations.CreateModel(
            name='BasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_base', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix de base')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='base_price', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Prix de base',
                'verbose_name_plural': 'Prix de base',
                'ordering': ['product__nom'],
            },
        ),
    ]
