# Generated by Django 4.2.8 on 2026-01-02 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_seuil_stock'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('nom', 'unite_vente')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='marque',
        ),
    ]
