# Generated by Django 4.2.8 on 2026-01-01 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100, unique=True, verbose_name='Référence')),
                ('date_arrivee_estimee', models.DateField(verbose_name="Date d'arrivée estimée")),
                ('date_arrivee_reelle', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée réelle")),
                ('statut', models.CharField(choices=[('PREVU', 'Prévu'), ('EN_COURS', 'En cours'), ('DECHARGE', 'Déchargé'), ('VALIDE', 'Validé')], default='PREVU', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
            ],
            options={
                'verbose_name': 'Conteneur',
                'verbose_name_plural': 'Conteneurs',
                'ordering': ['-date_arrivee_estimee', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManifestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_prevue', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité prévue')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Ligne manifest (prévu)',
                'verbose_name_plural': 'Lignes manifest (prévu)',
                'ordering': ['container', 'product__nom'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_recue', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité reçue')),
                ('casse', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Casse')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Ligne réception (réel)',
                'verbose_name_plural': 'Lignes réception (réel)',
                'ordering': ['container', 'product__nom'],
            },
        ),
        migrations.CreateModel(
            name='UnloadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_personnes', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de personnes')),
                ('somme_allouee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Somme allouée')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('container', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unloading_session', to='containers.container', verbose_name='Conteneur')),
            ],
            options={
                'verbose_name': 'Session de déchargement',
                'verbose_name_plural': 'Sessions de déchargement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnloadingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('START', 'Début'), ('PAUSE', 'Pause'), ('RESUME', 'Reprise'), ('END', 'Fin'), ('EDIT', 'Modification')], max_length=20, verbose_name='Type')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='containers.unloadingsession', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Événement de déchargement',
                'verbose_name_plural': 'Événements de déchargement',
                'ordering': ['-timestamp'],
            },
        ),
    ]
