# Generated by Django 4.2.8 on 2026-01-01 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('containers', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unloadingevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unloading_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='receivedline',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_lines', to='containers.container', verbose_name='Conteneur'),
        ),
        migrations.AddField(
            model_name='receivedline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='manifestline',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_lines', to='containers.container', verbose_name='Conteneur'),
        ),
        migrations.AddField(
            model_name='manifestline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manifest_lines', to='catalog.product', verbose_name='Produit'),
        ),
        migrations.AddField(
            model_name='container',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_containers', to=settings.AUTH_USER_MODEL, verbose_name='Validé par'),
        ),
        migrations.AddIndex(
            model_name='unloadingevent',
            index=models.Index(fields=['session', 'timestamp'], name='containers__session_22b698_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='receivedline',
            unique_together={('container', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='manifestline',
            unique_together={('container', 'product')},
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['statut'], name='containers__statut_3c7419_idx'),
        ),
        migrations.AddIndex(
            model_name='container',
            index=models.Index(fields=['date_arrivee_estimee'], name='containers__date_ar_9e6e38_idx'),
        ),
    ]
