# Generated by Django 4.2.8 on 2026-01-01 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('entreprise', models.CharField(blank=True, max_length=200, verbose_name='Entreprise')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('siret', models.CharField(blank=True, max_length=14, verbose_name='SIRET')),
                ('tva_intracommunautaire', models.CharField(blank=True, max_length=20, verbose_name='TVA intracommunautaire')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ClientPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_prices', to='clients.client', verbose_name='Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_prices', to='catalog.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Prix client',
                'verbose_name_plural': 'Prix clients',
                'ordering': ['client__nom', 'product__nom'],
            },
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['nom', 'prenom'], name='clients_cli_nom_f99d14_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['entreprise'], name='clients_cli_entrepr_cbe1bd_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['actif'], name='clients_cli_actif_a04af9_idx'),
        ),
        migrations.AddIndex(
            model_name='clientprice',
            index=models.Index(fields=['client', 'product'], name='clients_cli_client__4ea953_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clientprice',
            unique_together={('client', 'product')},
        ),
    ]
